{{- if .Values.s3.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backupRestore.s3SecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "backupRestore.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- with .Values.s3}}
  {{- if .credentialSecretName }}
  credentialSecretName: {{ .credentialSecretName }} 
  {{- end }}
  {{- if .region }}
  region: {{ .region }}
  {{- end }}
  bucketName: {{ .bucketName }}
  {{- if .folder }}
  folder: {{ .folder }} 
  {{- end }}
  endpoint: {{ .endpoint }}
  {{- if .endpointCA }} 
  endpointCA: {{ .endpointCA }} 
  {{- end }}
  {{- if .insecureTLSSkipVerify }}
  insecureTLSSkipVerify: {{ .insecureTLSSkipVerify }} 
  {{- end }}
  {{- end}}
{{ end }}
