apiVersion: v1
appVersion: v0.0.1-rc6
description: Helm chart for installing the rancher backup-restore-operator
name: backup-restore-operator
version: 0.0.1
annotations:
  catalog.cattle.io/certified: rancher
  catalog.cattle.io/namespace: cattle-resources-system
  catalog.cattle.io/release-name: backup-restore-operator
  catalog.cattle.io/ui-component: backup-restore-operator
